<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CustomLoginHandler' => 'src/CustomLoginHandler.php',
    'GerritApplication' => 'src/GerritApplication.php',
    'GerritChangeIdField' => 'src/GerritChangeIdField.php',
    'GerritProjectController' => 'src/GerritProjectController.php',
    'LDAPUserpageCustomField' => 'src/LDAPUserpageCustomField.php',
    'MediaWikiUserpageCustomField' => 'src/MediaWikiUserpageCustomField.php',
    'PhabricatorMediaWikiAuthProvider' => 'src/PhabricatorMediaWikiAuthProvider.php',
    'PhutilMediaWikiAuthAdapter' => 'src/PhutilMediaWikiAuthAdapter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'CustomLoginHandler' => 'PhabricatorAuthLoginHandler',
    'GerritApplication' => 'PhabricatorApplication',
    'GerritChangeIdField' => 'PhabricatorCommitCustomField',
    'GerritProjectController' => 'PhabricatorController',
    'LDAPUserpageCustomField' => 'PhabricatorUserCustomField',
    'MediaWikiUserpageCustomField' => 'PhabricatorUserCustomField',
    'PhabricatorMediaWikiAuthProvider' => 'PhabricatorOAuth1AuthProvider',
    'PhutilMediaWikiAuthAdapter' => 'PhutilOAuth1AuthAdapter',
  ),
));
